# .github/workflows/codespace-startup.yml
name: Codespace Startup
on:
  codespace_startup:
    types: [started]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt